### ISSUE TITLE
Upgrade to CentOS 8 - todo list

### ISSUE THREAD

**Issue by cmd-ntrf** [ComputeCanada/puppet-magic_castle#17]
List of problem observed when using puppet-magic_castle with a CentOS 8 image.
- [x] [mgmt1] `derdanne-nfs` 2.1.2 does not support CentOS 8 [issue #105](https://github.com/derdanne/puppet-nfs/pull/105)
- [x] puppet-firewall 2.0.0 does not support CentOS 8. Update to 2.2.0
- [x] Slurm19 needs to be built for CentOS 8.
- [x] Slurm19 needs libaec, that is in PowerTools repo, which is not enabled by default
- [x] [mgmt1]`ipa-server` cannot be found by `dnf` unless idm repo is enabled in appstream.
- [x] dnf cannot find `yum-plugin-priorities`
- [x] EPEL yumrepo url format has changed for RHEL8 and needs to be updated.
- [x] Packages that cannot be found without EPEL fix: `munge`, `haveged`, `xauth`, `mariadb-server`.
- [x] `pdsh` is no longer in EPEL
- [x] `python` no longer exists. The `ipa_create_user` script header needs to be changed from `#!/usr/bin/env python` to `#!/usr/libexec/platform-python`.
- [x] [login] dnf Unable to find a match: fail2ban-server
- [x] [node] Error: Unable to find a match: nvidia-xconfig-latest-dkms
- [x] [mgmt1] The command to modify ipa web server SSL certificate no longer works.
- [x] [login1] SELinux prevent job submission with sbatch and interactive job allocation to work with `salloc`.
- [x] The `id` command provided by CVMFS NIX does not work properly with CentOS8. It is potentially too old. CentOS 8 coreutils version is 8.30, while Nix version is 8.25. This causes a problem when starting interactive job, the username cannot be determined and the shell session is from 'I am without a name'.
- [x] postrun script emails are blocked by something internal. sendmail is being denied connection to localhost.
